### ISSUE TITLE
TypeError: Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/kramed#29]
Hi I'm getting the following error due building my book on gitbook

```
TypeError: Cannot call method 'toLowerCase' of undefined
Please report this to https://github.com/GitbookIO/kramed. (In file 'module_0x1__basic/README.md')
```

please advice

**Comment by AaronO** [comment]
@KINGSABRI What's your book ?

**Comment by KINGSABRI** [comment]
The book name is: Rubyfu under KINGSABRI user

**Comment by AaronO** [comment]
@KINGSABRI Thanks a lot.

I fixed the issue with 9faeacb81d928a4e6f44f7a991630fb277507833 and 0723a8c54c6e2bbe6233a90b3b67ef1e09227779.

I accidentally introduced those regressions last night (while fixing something else), I've added tests, so that we won't break it in the future.

We'll likely ship a new release to production in ~30mn to 1h

**Comment by KINGSABRI** [comment]
I'm getting the same issue :(

**Comment by AaronO** [comment]
@KINGSABRI It's not yet in production, but will be soon. I'll update here when it is :)

**Comment by KINGSABRI** [comment]
@AaronO Thanks man I wish we can fix it soon since the book will published at the first few days of 2016 and these days have a lot of changes 

appreciated!

**Comment by AaronO** [comment]
@KINGSABRI The fix is live now :) It was just a matter of minutes not months ;)

**Comment by KINGSABRI** [comment]
@AaronO Yup, it's working now 

Thanks!
